2023-04-30 20:12 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 779, in _read_query_result
    result.read()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'eduusdt-f-d' at line 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Database\SQL_operate.py", line 79, in read_Dateframe
    return pd.read_sql(text_msg, con=conn)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pandas\io\sql.py", line 661, in read_sql
    return pandas_sql.read_query(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pandas\io\sql.py", line 1736, in read_query
    result = self.execute(sql, params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pandas\io\sql.py", line 1560, in execute
    return self.con.exec_driver_sql(sql, *args)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1760, in exec_driver_sql
    return self._exec_driver_sql(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1669, in _exec_driver_sql
    ret = self._execute_context(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\util\compat.py", line 210, in raise_
    raise exception
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 779, in _read_query_result
    result.read()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'eduusdt-f-d' at line 1")
[SQL: eduusdt-f-d]
(Background on this error at: https://sqlalche.me/e/14/f405)

2023-04-30 20:14 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 779, in _read_query_result
    result.read()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'eduusdt-f-d' at line 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Database\SQL_operate.py", line 79, in read_Dateframe
    return pd.read_sql(text_msg, con=conn)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pandas\io\sql.py", line 661, in read_sql
    return pandas_sql.read_query(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pandas\io\sql.py", line 1736, in read_query
    result = self.execute(sql, params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pandas\io\sql.py", line 1560, in execute
    return self.con.exec_driver_sql(sql, *args)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1760, in exec_driver_sql
    return self._exec_driver_sql(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1669, in _exec_driver_sql
    ret = self._execute_context(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\util\compat.py", line 210, in raise_
    raise exception
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 779, in _read_query_result
    result.read()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'eduusdt-f-d' at line 1")
[SQL: eduusdt-f-d]
(Background on this error at: https://sqlalche.me/e/14/f405)

2023-04-30 20:26 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 779, in _read_query_result
    result.read()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'eduusdt-f-d' at line 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Database\SQL_operate.py", line 79, in read_Dateframe
    return pd.read_sql(text_msg, con=conn)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pandas\io\sql.py", line 661, in read_sql
    return pandas_sql.read_query(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pandas\io\sql.py", line 1736, in read_query
    result = self.execute(sql, params)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pandas\io\sql.py", line 1560, in execute
    return self.con.exec_driver_sql(sql, *args)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1760, in exec_driver_sql
    return self._exec_driver_sql(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1669, in _exec_driver_sql
    ret = self._execute_context(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\util\compat.py", line 210, in raise_
    raise exception
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 779, in _read_query_result
    result.read()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'eduusdt-f-d' at line 1")
[SQL: eduusdt-f-d]
(Background on this error at: https://sqlalche.me/e/14/f405)

2023-04-30 22:20 ERROR 資料讀取結束 
2023-04-30 22:21 ERROR 開始進入回測 
2023-04-30 22:21 ERROR 目前交易狀態,校正之後 {'BTCUSDT-15K-OB': [1.0, 0.15556790601319093], 'XMRUSDT-15K-OB': [1.0, 20.050249176675358], 'MKRUSDT-15K-OB-VCP': [0.0, 0.0], 'AAVEUSDT-15K-OB': [0.0, 0.0], 'AAVEUSDT-15K-OB-VCP': [0.0, 0.0], 'ZECUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB': [0.0, 0.0], 'MKRUSDT-15K-OB': [0.0, 0.0], 'LTCUSDT-15K-OB-VCP': [0.0, 0.0], 'BNBUSDT-15K-OB': [0.0, 0.0], 'SOLUSDT-15K-OB': [0.0, 0.0], 'XMRUSDT-15K-OB-VCP': [1.0, 25.150693265534397], 'LTCUSDT-15K-OB': [0.0, 0.0], 'COMPUSDT-15K-OB-VCP': [1.0, 93.62807655868738], 'BTCDOMUSDT-15K-OB-VCP': [1.0, 3.2755831789748955], 'COMPUSDT-15K-OB': [1.0, 61.08475283392126], 'BNBUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB-VCP': [0.0, 0.0], 'BTCUSDT-15K-OB-VCP': [1.0, 1.8974102177740213], 'ZECUSDT-15K-OB': [0.0, 0.0], 'BTCDOMUSDT-15K-OB': [1.0, 1.7179139759924507], 'SOLUSDT-15K-OB-VCP': [0.0, 0.0]} 
2023-04-30 22:21 ERROR 目前binance交易所內的部位狀態: {'XMRUSDT': '45.380', 'COMPUSDT': '155.340', 'BTCDOMUSDT': '5.010', 'BTCUSDT': '2.061'} 
2023-04-30 22:21 ERROR 差異單 {'BTCUSDT': -0.011, 'XMRUSDT': -0.179, 'COMPUSDT': -0.629, 'BTCDOMUSDT': -0.019} 
2023-04-30 22:21 ERROR 時間差 51.35907030105591 
2023-04-30 22:22 ERROR 開始進入回測 
2023-04-30 22:22 ERROR 目前交易狀態,校正之後 {'BTCUSDT-15K-OB': [1.0, 0.15556790601319093], 'XMRUSDT-15K-OB': [1.0, 20.050249176675358], 'MKRUSDT-15K-OB-VCP': [0.0, 0.0], 'AAVEUSDT-15K-OB': [0.0, 0.0], 'AAVEUSDT-15K-OB-VCP': [0.0, 0.0], 'ZECUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB': [0.0, 0.0], 'MKRUSDT-15K-OB': [0.0, 0.0], 'LTCUSDT-15K-OB-VCP': [0.0, 0.0], 'BNBUSDT-15K-OB': [0.0, 0.0], 'SOLUSDT-15K-OB': [0.0, 0.0], 'XMRUSDT-15K-OB-VCP': [1.0, 25.150693265534397], 'LTCUSDT-15K-OB': [0.0, 0.0], 'COMPUSDT-15K-OB-VCP': [1.0, 93.62807655868738], 'BTCDOMUSDT-15K-OB-VCP': [1.0, 3.2755831789748955], 'COMPUSDT-15K-OB': [1.0, 61.08475283392126], 'BNBUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB-VCP': [0.0, 0.0], 'BTCUSDT-15K-OB-VCP': [1.0, 1.8974102177740213], 'ZECUSDT-15K-OB': [0.0, 0.0], 'BTCDOMUSDT-15K-OB': [1.0, 1.7179139759924507], 'SOLUSDT-15K-OB-VCP': [0.0, 0.0]} 
2023-04-30 22:22 ERROR 目前binance交易所內的部位狀態: {'XMRUSDT': '45.380', 'COMPUSDT': '155.340', 'BTCDOMUSDT': '5.010', 'BTCUSDT': '2.061'} 
2023-04-30 22:22 ERROR 差異單 {'BTCUSDT': -0.011, 'XMRUSDT': -0.179, 'COMPUSDT': -0.629, 'BTCDOMUSDT': -0.019} 
2023-04-30 22:22 ERROR 時間差 44.430805921554565 
2023-04-30 22:23 ERROR 開始進入回測 
2023-04-30 22:23 ERROR 目前交易狀態,校正之後 {'BTCUSDT-15K-OB': [1.0, 0.15556790601319093], 'XMRUSDT-15K-OB': [1.0, 20.050249176675358], 'MKRUSDT-15K-OB-VCP': [0.0, 0.0], 'AAVEUSDT-15K-OB': [0.0, 0.0], 'AAVEUSDT-15K-OB-VCP': [0.0, 0.0], 'ZECUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB': [0.0, 0.0], 'MKRUSDT-15K-OB': [0.0, 0.0], 'LTCUSDT-15K-OB-VCP': [0.0, 0.0], 'BNBUSDT-15K-OB': [0.0, 0.0], 'SOLUSDT-15K-OB': [0.0, 0.0], 'XMRUSDT-15K-OB-VCP': [1.0, 25.150693265534397], 'LTCUSDT-15K-OB': [0.0, 0.0], 'COMPUSDT-15K-OB-VCP': [1.0, 93.62807655868738], 'BTCDOMUSDT-15K-OB-VCP': [1.0, 3.2755831789748955], 'COMPUSDT-15K-OB': [1.0, 61.08475283392126], 'BNBUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB-VCP': [0.0, 0.0], 'BTCUSDT-15K-OB-VCP': [1.0, 1.8974102177740213], 'ZECUSDT-15K-OB': [0.0, 0.0], 'BTCDOMUSDT-15K-OB': [1.0, 1.7179139759924507], 'SOLUSDT-15K-OB-VCP': [0.0, 0.0]} 
2023-04-30 22:23 ERROR 目前binance交易所內的部位狀態: {'XMRUSDT': '45.380', 'COMPUSDT': '155.340', 'BTCDOMUSDT': '5.010', 'BTCUSDT': '2.061'} 
2023-04-30 22:23 ERROR 差異單 {'BTCUSDT': -0.011, 'XMRUSDT': -0.179, 'COMPUSDT': -0.629, 'BTCDOMUSDT': -0.019} 
2023-04-30 22:23 ERROR 時間差 44.22344160079956 
2023-04-30 22:24 ERROR 開始進入回測 
2023-04-30 22:24 ERROR 目前交易狀態,校正之後 {'BTCUSDT-15K-OB': [1.0, 0.15556790601319093], 'XMRUSDT-15K-OB': [1.0, 20.050249176675358], 'MKRUSDT-15K-OB-VCP': [0.0, 0.0], 'AAVEUSDT-15K-OB': [0.0, 0.0], 'AAVEUSDT-15K-OB-VCP': [0.0, 0.0], 'ZECUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB': [0.0, 0.0], 'MKRUSDT-15K-OB': [0.0, 0.0], 'LTCUSDT-15K-OB-VCP': [0.0, 0.0], 'BNBUSDT-15K-OB': [0.0, 0.0], 'SOLUSDT-15K-OB': [0.0, 0.0], 'XMRUSDT-15K-OB-VCP': [1.0, 25.150693265534397], 'LTCUSDT-15K-OB': [0.0, 0.0], 'COMPUSDT-15K-OB-VCP': [1.0, 93.62807655868738], 'BTCDOMUSDT-15K-OB-VCP': [1.0, 3.2755831789748955], 'COMPUSDT-15K-OB': [1.0, 61.08475283392126], 'BNBUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB-VCP': [0.0, 0.0], 'BTCUSDT-15K-OB-VCP': [1.0, 1.8974102177740213], 'ZECUSDT-15K-OB': [0.0, 0.0], 'BTCDOMUSDT-15K-OB': [1.0, 1.7179139759924507], 'SOLUSDT-15K-OB-VCP': [0.0, 0.0]} 
2023-04-30 22:24 ERROR 目前binance交易所內的部位狀態: {'XMRUSDT': '45.380', 'COMPUSDT': '155.340', 'BTCDOMUSDT': '5.010', 'BTCUSDT': '2.061'} 
2023-04-30 22:24 ERROR 差異單 {'BTCUSDT': -0.011, 'XMRUSDT': -0.179, 'COMPUSDT': -0.629, 'BTCDOMUSDT': -0.019} 
2023-04-30 22:24 ERROR 時間差 44.59371328353882 
2023-04-30 22:25 ERROR 開始進入回測 
2023-04-30 22:25 ERROR 目前交易狀態,校正之後 {'BTCUSDT-15K-OB': [1.0, 0.15556790601319093], 'XMRUSDT-15K-OB': [1.0, 20.050249176675358], 'MKRUSDT-15K-OB-VCP': [0.0, 0.0], 'AAVEUSDT-15K-OB': [0.0, 0.0], 'AAVEUSDT-15K-OB-VCP': [0.0, 0.0], 'ZECUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB': [0.0, 0.0], 'MKRUSDT-15K-OB': [0.0, 0.0], 'LTCUSDT-15K-OB-VCP': [0.0, 0.0], 'BNBUSDT-15K-OB': [0.0, 0.0], 'SOLUSDT-15K-OB': [0.0, 0.0], 'XMRUSDT-15K-OB-VCP': [1.0, 25.150693265534397], 'LTCUSDT-15K-OB': [0.0, 0.0], 'COMPUSDT-15K-OB-VCP': [1.0, 93.62807655868738], 'BTCDOMUSDT-15K-OB-VCP': [1.0, 3.2755831789748955], 'COMPUSDT-15K-OB': [1.0, 61.08475283392126], 'BNBUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB-VCP': [0.0, 0.0], 'BTCUSDT-15K-OB-VCP': [1.0, 1.8974102177740213], 'ZECUSDT-15K-OB': [0.0, 0.0], 'BTCDOMUSDT-15K-OB': [1.0, 1.7179139759924507], 'SOLUSDT-15K-OB-VCP': [0.0, 0.0]} 
2023-04-30 22:25 ERROR 目前binance交易所內的部位狀態: {'XMRUSDT': '45.380', 'COMPUSDT': '155.340', 'BTCDOMUSDT': '5.010', 'BTCUSDT': '2.061'} 
2023-04-30 22:25 ERROR 差異單 {'BTCUSDT': -0.011, 'XMRUSDT': -0.179, 'COMPUSDT': -0.629, 'BTCDOMUSDT': -0.019} 
2023-04-30 22:25 ERROR 時間差 44.42359924316406 
2023-04-30 22:26 ERROR 開始進入回測 
2023-04-30 22:26 ERROR 目前交易狀態,校正之後 {'BTCUSDT-15K-OB': [1.0, 0.15556790601319093], 'XMRUSDT-15K-OB': [1.0, 20.050249176675358], 'MKRUSDT-15K-OB-VCP': [0.0, 0.0], 'AAVEUSDT-15K-OB': [0.0, 0.0], 'AAVEUSDT-15K-OB-VCP': [0.0, 0.0], 'ZECUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB': [0.0, 0.0], 'MKRUSDT-15K-OB': [0.0, 0.0], 'LTCUSDT-15K-OB-VCP': [0.0, 0.0], 'BNBUSDT-15K-OB': [0.0, 0.0], 'SOLUSDT-15K-OB': [0.0, 0.0], 'XMRUSDT-15K-OB-VCP': [1.0, 25.150693265534397], 'LTCUSDT-15K-OB': [0.0, 0.0], 'COMPUSDT-15K-OB-VCP': [1.0, 93.62807655868738], 'BTCDOMUSDT-15K-OB-VCP': [1.0, 3.2755831789748955], 'COMPUSDT-15K-OB': [1.0, 61.08475283392126], 'BNBUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB-VCP': [0.0, 0.0], 'BTCUSDT-15K-OB-VCP': [1.0, 1.8974102177740213], 'ZECUSDT-15K-OB': [0.0, 0.0], 'BTCDOMUSDT-15K-OB': [1.0, 1.7179139759924507], 'SOLUSDT-15K-OB-VCP': [0.0, 0.0]} 
2023-04-30 22:26 ERROR 目前binance交易所內的部位狀態: {'XMRUSDT': '45.380', 'COMPUSDT': '155.340', 'BTCDOMUSDT': '5.010', 'BTCUSDT': '2.061'} 
2023-04-30 22:26 ERROR 差異單 {'BTCUSDT': -0.011, 'XMRUSDT': -0.179, 'COMPUSDT': -0.629, 'BTCDOMUSDT': -0.019} 
2023-04-30 22:26 ERROR 時間差 43.84695243835449 
2023-04-30 22:27 ERROR 開始進入回測 
2023-04-30 22:27 ERROR 目前交易狀態,校正之後 {'BTCUSDT-15K-OB': [1.0, 0.15556790601319093], 'XMRUSDT-15K-OB': [1.0, 20.050249176675358], 'MKRUSDT-15K-OB-VCP': [0.0, 0.0], 'AAVEUSDT-15K-OB': [0.0, 0.0], 'AAVEUSDT-15K-OB-VCP': [0.0, 0.0], 'ZECUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB': [0.0, 0.0], 'MKRUSDT-15K-OB': [0.0, 0.0], 'LTCUSDT-15K-OB-VCP': [0.0, 0.0], 'BNBUSDT-15K-OB': [0.0, 0.0], 'SOLUSDT-15K-OB': [0.0, 0.0], 'XMRUSDT-15K-OB-VCP': [1.0, 25.150693265534397], 'LTCUSDT-15K-OB': [0.0, 0.0], 'COMPUSDT-15K-OB-VCP': [1.0, 93.62807655868738], 'BTCDOMUSDT-15K-OB-VCP': [1.0, 3.2755831789748955], 'COMPUSDT-15K-OB': [1.0, 61.08475283392126], 'BNBUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB-VCP': [0.0, 0.0], 'BTCUSDT-15K-OB-VCP': [1.0, 1.8974102177740213], 'ZECUSDT-15K-OB': [0.0, 0.0], 'BTCDOMUSDT-15K-OB': [1.0, 1.7179139759924507], 'SOLUSDT-15K-OB-VCP': [0.0, 0.0]} 
2023-04-30 22:27 ERROR 目前binance交易所內的部位狀態: {'XMRUSDT': '45.380', 'COMPUSDT': '155.340', 'BTCDOMUSDT': '5.010', 'BTCUSDT': '2.061'} 
2023-04-30 22:27 ERROR 差異單 {'BTCUSDT': -0.011, 'XMRUSDT': -0.179, 'COMPUSDT': -0.629, 'BTCDOMUSDT': -0.019} 
2023-04-30 22:27 ERROR 時間差 45.15256643295288 
2023-04-30 22:28 ERROR 開始進入回測 
2023-04-30 22:28 ERROR 目前交易狀態,校正之後 {'BTCUSDT-15K-OB': [1.0, 0.15556790601319093], 'XMRUSDT-15K-OB': [1.0, 20.050249176675358], 'MKRUSDT-15K-OB-VCP': [0.0, 0.0], 'AAVEUSDT-15K-OB': [0.0, 0.0], 'AAVEUSDT-15K-OB-VCP': [0.0, 0.0], 'ZECUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB': [0.0, 0.0], 'MKRUSDT-15K-OB': [0.0, 0.0], 'LTCUSDT-15K-OB-VCP': [0.0, 0.0], 'BNBUSDT-15K-OB': [0.0, 0.0], 'SOLUSDT-15K-OB': [0.0, 0.0], 'XMRUSDT-15K-OB-VCP': [1.0, 25.150693265534397], 'LTCUSDT-15K-OB': [0.0, 0.0], 'COMPUSDT-15K-OB-VCP': [1.0, 93.62807655868738], 'BTCDOMUSDT-15K-OB-VCP': [1.0, 3.2755831789748955], 'COMPUSDT-15K-OB': [1.0, 61.08475283392126], 'BNBUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB-VCP': [0.0, 0.0], 'BTCUSDT-15K-OB-VCP': [1.0, 1.8974102177740213], 'ZECUSDT-15K-OB': [0.0, 0.0], 'BTCDOMUSDT-15K-OB': [1.0, 1.7179139759924507], 'SOLUSDT-15K-OB-VCP': [0.0, 0.0]} 
2023-04-30 22:28 ERROR 目前binance交易所內的部位狀態: {'XMRUSDT': '45.380', 'COMPUSDT': '155.340', 'BTCDOMUSDT': '5.010', 'BTCUSDT': '2.061'} 
2023-04-30 22:28 ERROR 差異單 {'BTCUSDT': -0.011, 'XMRUSDT': -0.179, 'COMPUSDT': -0.629, 'BTCDOMUSDT': -0.019} 
2023-04-30 22:28 ERROR 時間差 46.38216161727905 
2023-04-30 22:29 ERROR 開始進入回測 
2023-04-30 22:29 ERROR 目前交易狀態,校正之後 {'BTCUSDT-15K-OB': [1.0, 0.15556790601319093], 'XMRUSDT-15K-OB': [1.0, 20.050249176675358], 'MKRUSDT-15K-OB-VCP': [0.0, 0.0], 'AAVEUSDT-15K-OB': [0.0, 0.0], 'AAVEUSDT-15K-OB-VCP': [0.0, 0.0], 'ZECUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB': [0.0, 0.0], 'MKRUSDT-15K-OB': [0.0, 0.0], 'LTCUSDT-15K-OB-VCP': [0.0, 0.0], 'BNBUSDT-15K-OB': [0.0, 0.0], 'SOLUSDT-15K-OB': [0.0, 0.0], 'XMRUSDT-15K-OB-VCP': [1.0, 25.150693265534397], 'LTCUSDT-15K-OB': [0.0, 0.0], 'COMPUSDT-15K-OB-VCP': [1.0, 93.62807655868738], 'BTCDOMUSDT-15K-OB-VCP': [1.0, 3.2755831789748955], 'COMPUSDT-15K-OB': [1.0, 61.08475283392126], 'BNBUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB-VCP': [0.0, 0.0], 'BTCUSDT-15K-OB-VCP': [1.0, 1.8974102177740213], 'ZECUSDT-15K-OB': [0.0, 0.0], 'BTCDOMUSDT-15K-OB': [1.0, 1.7179139759924507], 'SOLUSDT-15K-OB-VCP': [0.0, 0.0]} 
2023-04-30 22:29 ERROR 目前binance交易所內的部位狀態: {'XMRUSDT': '45.380', 'COMPUSDT': '155.340', 'BTCDOMUSDT': '5.010', 'BTCUSDT': '2.061'} 
2023-04-30 22:29 ERROR 差異單 {'BTCUSDT': -0.011, 'XMRUSDT': -0.179, 'COMPUSDT': -0.629, 'BTCDOMUSDT': -0.019} 
2023-04-30 22:29 ERROR 時間差 44.98556661605835 
2023-04-30 22:30 ERROR 開始進入回測 
2023-04-30 22:30 ERROR 目前交易狀態,校正之後 {'BTCUSDT-15K-OB': [1.0, 0.15556790601319093], 'XMRUSDT-15K-OB': [1.0, 20.050249176675358], 'MKRUSDT-15K-OB-VCP': [0.0, 0.0], 'AAVEUSDT-15K-OB': [0.0, 0.0], 'AAVEUSDT-15K-OB-VCP': [0.0, 0.0], 'ZECUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB': [0.0, 0.0], 'MKRUSDT-15K-OB': [0.0, 0.0], 'LTCUSDT-15K-OB-VCP': [0.0, 0.0], 'BNBUSDT-15K-OB': [0.0, 0.0], 'SOLUSDT-15K-OB': [0.0, 0.0], 'XMRUSDT-15K-OB-VCP': [1.0, 25.150693265534397], 'LTCUSDT-15K-OB': [0.0, 0.0], 'COMPUSDT-15K-OB-VCP': [1.0, 93.62807655868738], 'BTCDOMUSDT-15K-OB-VCP': [1.0, 3.2755831789748955], 'COMPUSDT-15K-OB': [1.0, 61.08475283392126], 'BNBUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB-VCP': [0.0, 0.0], 'BTCUSDT-15K-OB-VCP': [1.0, 1.8974102177740213], 'ZECUSDT-15K-OB': [0.0, 0.0], 'BTCDOMUSDT-15K-OB': [1.0, 1.7179139759924507], 'SOLUSDT-15K-OB-VCP': [0.0, 0.0]} 
2023-04-30 22:30 ERROR 目前binance交易所內的部位狀態: {'XMRUSDT': '45.380', 'COMPUSDT': '155.340', 'BTCDOMUSDT': '5.010', 'BTCUSDT': '2.061'} 
2023-04-30 22:30 ERROR 差異單 {'BTCUSDT': -0.011, 'XMRUSDT': -0.179, 'COMPUSDT': -0.629, 'BTCDOMUSDT': -0.019} 
2023-04-30 22:30 ERROR 時間差 44.75076150894165 
2023-04-30 22:31 ERROR 開始進入回測 
2023-04-30 22:31 ERROR 目前交易狀態,校正之後 {'BTCUSDT-15K-OB': [1.0, 0.15556790601319093], 'XMRUSDT-15K-OB': [1.0, 20.050249176675358], 'MKRUSDT-15K-OB-VCP': [0.0, 0.0], 'AAVEUSDT-15K-OB': [0.0, 0.0], 'AAVEUSDT-15K-OB-VCP': [0.0, 0.0], 'ZECUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB': [0.0, 0.0], 'MKRUSDT-15K-OB': [0.0, 0.0], 'LTCUSDT-15K-OB-VCP': [0.0, 0.0], 'BNBUSDT-15K-OB': [0.0, 0.0], 'SOLUSDT-15K-OB': [0.0, 0.0], 'XMRUSDT-15K-OB-VCP': [1.0, 25.150693265534397], 'LTCUSDT-15K-OB': [0.0, 0.0], 'COMPUSDT-15K-OB-VCP': [1.0, 93.62807655868738], 'BTCDOMUSDT-15K-OB-VCP': [1.0, 3.2755831789748955], 'COMPUSDT-15K-OB': [1.0, 61.08475283392126], 'BNBUSDT-15K-OB-VCP': [0.0, 0.0], 'ETHUSDT-15K-OB-VCP': [0.0, 0.0], 'BTCUSDT-15K-OB-VCP': [1.0, 1.8974102177740213], 'ZECUSDT-15K-OB': [0.0, 0.0], 'BTCDOMUSDT-15K-OB': [1.0, 1.7179139759924507], 'SOLUSDT-15K-OB-VCP': [0.0, 0.0]} 
2023-04-30 22:31 ERROR 目前binance交易所內的部位狀態: {'XMRUSDT': '45.380', 'COMPUSDT': '155.340', 'BTCDOMUSDT': '5.010', 'BTCUSDT': '2.061'} 
2023-04-30 22:31 ERROR 差異單 {'BTCUSDT': -0.011, 'XMRUSDT': -0.179, 'COMPUSDT': -0.629, 'BTCDOMUSDT': -0.019} 
2023-04-30 22:31 ERROR 時間差 44.29894161224365 
2023-04-30 22:31 ERROR 緊急狀況處理-交易次數過多 
